# Four UR5e with Robotiq 2F-85 (same layout as lab.yaml).
ur_type: ur5e
semantic_description_file: srdf/ur_robotiq.srdf.xacro
gazebo_gui: "true"
world_file: lab_table_coke.sdf
robot_namespace_prefix: ur
launch_rviz_first_robot: "true"
launch_servo: "false"
publish_robot_description_semantic: "true"
use_robotiq_gripper: "true"
robot_positions:
  - x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  - x: 2.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  - x: 0.0
    y: 2.0
    z: 0.0
    yaw: 1.57
  - x: 2.0
    y: 2.0
    z: 0.0
    yaw: 1.57
